on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: 

name: Tests
jobs:
  tests:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-8x16-with-cache
      - nscloud-cache-size-5gb
      - nscloud-cache-tag-gha-demo-remix
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Local cache for API dependencies
        id: api-cache
        uses: MasterworksIO/action-local-cache@2
        with:
          path: './node_modules/'
          key: 'npm-cache'

      - name: Install dependencies
        run: npm install
        if: steps.api-cache.outputs.cache-hit != 'true'

      - name: NPM tests
        run: npm run test
    